title: OUROBOROS
author: Apostolos Stamenos
contact_url: /intake
tutoring_url: https://www.wyzant.com/refer/tutor/86925781/?utm_source=TREF&utm_campaign=iphone&utm_content=tutorapp&utm_medium=share
github_url: https://github.com/OUROBOROS-Consulting
linkedin_url: https://www.linkedin.com/in/apostolos-stamenos
url: "https://ouroborosconsulting.org"

collections:
  services:
    output: true
    permalink: /services/:slug/
  essays:
    output: true
    permalink: /essays/:slug/
  projects:
    output: true
    permalink: /projects/:slug/
  notes:
    output: true
    permalink: /notes/:slug/
  linkedin:
    output: true
    permalink: /posts/:year/:slug/
  resources:
    output: true
    permalink: /resources/:slug/
  case_studies:
    output: true
    permalink: /work/:slug/
  psas:
    output: true
    permalink: /work/psas/:slug/
  about:
    output: true
    permalink: /:slug
  announcements:
    output: false

# build settings
exclude: ["script", "vendor", "bower.json", "Gemfile", "Gemfile.lock", "Rakefile", "readme.md", "package.json", "node_modules"]
markdown: kramdown

# SCSS processing
sass:
  load_paths:
    - node_modules
#plugins:
#  - jekyll-avatar
#  - jekyll-redirect-from
#  - jekyll-seo-tag
#  - jekyll-coffeescript
#  - jekyll-sitemap
#  - jekyll-octicons
