- title: Reason
  tag: Technology
  description: >
    gkkug kug ku
  reference: 
  link: "#"

- title: Autonomy
  tag: Technology
  description: >
    gkkug kug ku
  reference: 
  link: "#"
  
- title: Integrity
  tag: Technology
  description: >
    uid iugfvisguos v
  reference: 
  link: "#"

- title: Authenticity
  tag: Technology
  description: >
    jgiy
  reference: 
  link: "#"

- title: Security
  tag: Technology
  description: >
    know that I and other CDCers think you're fantastic. I hope we figure out how to put the crap behind us and move forward quickly.
  reference: 
  link: "#"

- title: Kindness
  tag: Technology
  description: >
    know that I and other CDCers think you're fantastic. I hope we figure out how to put the crap behind us and move forward quickly.
  reference: 
  link: "#"
